create view [dbo].[vTopWaitStatsByContext]
as
select
	[SPID],
	[Context],
	[DateFrom],
	[DateTo],
	[WaitType],
	[WaitTime],
	[NbrWaits],
	[AvgWaitTime],
	[WaitTimeTtl],
	[WaitTimePct]
from [dbo].[WaitStatsByContext]
where [WaitTime] > 0
  and [WaitType] not in (
		N'SOS_WORK_DISPATCHER',
		N'LOGMGR_QUEUE',
		N'BROKER_EVENTHANDLER',
		N'BROKER_RECEIVE_WAITFOR',
		N'BROKER_TASK_STOP',
		N'BROKER_TO_FLUSH',
		N'BROKER_TRANSMITTER',
		N'CHECKPOINT_QUEUE',
		N'CHKPT',
		N'CLR_AUTO_EVENT',
		N'CLR_MANUAL_EVENT',
		N'DIRTY_PAGE_POLL',
		N'DISPATCHER_QUEUE_SEMAPHORE',
		N'FT_IFTS_SCHEDULER_IDLE_WAIT',
		N'HADR_FILESTREAM_IOMGR_IOCOMPLETION',
		N'LAZYWRITER_SLEEP',
		N'ONDEMAND_TASK_QUEUE',
		N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP',
		N'QDS_ASYNC_QUEUE',
		N'REQUEST_FOR_DEADLOCK_SEARCH',
		N'RESOURCE_QUEUE',
		N'SLEEP_TASK',
		N'SLEEP_SYSTEMTASK',
		N'SP_SERVER_DIAGNOSTICS_SLEEP',
		N'SQLTRACE_BUFFER_FLUSH',
		N'WAITFOR',
		N'XE_DISPATCHER_WAIT',
		N'XE_TIMER_EVENT'
	)
go